export const SHOW_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

//handle change
export const HANDLE_CHANGE = 'HANDLE_CHANGE';

//change page
export const CHANGE_PAGE = 'CHANGE_PAGE';

//clear values
export const CLEAR_VALUES = 'CLEAR_VALUES';

//clear filters
export const CLEAR_FILTERS = 'CLEAR_FILTERS';

//current user
export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

//update user
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

//create job
export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';

//get jobs
export const GET_ALL_JOBS_REQUEST = 'GET_ALL_JOBS_REQUEST';
export const GET_ALL_JOBS_SUCCESS = 'GET_ALL_JOBS_SUCCESS';

//update job
 export const SET_EDIT_JOB = 'SET_EDIT_JOB';

 export const EDIT_JOB_REQUEST = 'EDIT_JOB_REQUEST';
 export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS';
 export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR';

 //delete job
 export const DELETE_JOB_REQUEST = 'DELETE_JOB_REQUEST';

 //stats
 export const SHOW_STATS_REQUEST = 'SHOW_STATS_REQUEST';
 export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS';